In [61]:
import numpy as np
import sympy as sy
import matplotlib.pyplot as plt

x,y,z=sy.symbols('x,y,z')

A=np.random.randint(100,size=(3,3))
print('\nMatriz A')
print(A)
print('\nMatriz de funciones')
F=np.random.randint(100,size=(3,1))
print(F)
print ('\nPrint de Variables')
X=np.array([x,y,z])
print(X)
print('\nA*X')
G=np.array(A*X)
print(G)

q=A[0,0]*X[0]+A[0,1]*X[1]+A[0,2]*X[2]
display(q)
w=A[1,0]*X[0]+A[1,1]*X[1]+A[1,2]*X[2]
display(w)
e=A[2,0]*X[0]+A[2,1]*X[1]+A[2,2]*X[2]
display(e)





Matriz A
[[38 99 29]
 [13 81  4]
 [58 81 82]]

Matriz de funciones
[[36]
 [84]
 [32]]

Print de Variables
[x y z]

A*X
[[38*x 99*y 29*z]
 [13*x 81*y 4*z]
 [58*x 81*y 82*z]]


38*x + 99*y + 29*z

13*x + 81*y + 4*z

58*x + 81*y + 82*z

In [8]:
import numpy as np
import sympy as sy
import matplotlib.pyplot as plt

x,y,z=sy.symbols('x,y,z')

A=np.random.randint(100,size=(3,3))
print('\nMatriz A')
print(A)
print('\nMatriz de funciones')
F=np.random.randint(100,size=(3))
print(F)
print ('\nPrint de Variables')
X=np.array([x,y,z])
print(X)
print('\nA*X')
def gauss(A,F):
    U=np.copy(A)
    G=np.copy(F)
    n=F.size
    for j in range (n-1):
        for i in range (j+1,n):
            m=U[i,j]/U[j,j]
            U[i,j:]=U[i,j:]-m*U[j,j:]
            G[i]=G[i]-m*G[j]
    return U,G



Matriz A
[[ 2 24 83]
 [27 81 87]
 [54 56 51]]

Matriz de funciones
[18 24 89]

Print de Variables
[x y z]

A*X


In [10]:
gauss(A,F)

(array([[    2,    24,    83],
        [    0,  -243, -1033],
        [    0,     0,   326]]),
 array([  18, -219,  136]))