In [56]:
import numpy as np
import sympy as sy
import matplotlib.pyplot as plt

x,y,z=sy.symbols('x,y,z')

A=np.random.randint(10,size=(3,3))
print('\nMatriz A')
print(A)
print('\nMatriz de funciones')
F=np.random.randint(10,size=(3))
print(F)
print ('\nPrint de Variables')
X=np.array([x,y,z])
print(X)
def gauss(A,F):
    U=np.copy(A)
    G=np.copy(F)
    n=F.size
    for j in range (n-1):
        for i in range (j+1,n):
            m=U[i,j]/U[j,j]
            U[i,j:]=U[i,j:]-m*U[j,j:]
            G[i]=G[i]-m*G[j]
    return U,G

def solucionatras(U1,G1):
    n=G1.size
    X=np.zeros(n)
    for i in reversed(range (n)):
        X[i]=G1[i]/U1[i,i]-np.dot(U1[i,i+1:],X[i+1:])
    return X
print('Entonces las nuevas matrices U,G')




Matriz A
[[9 0 9]
 [2 9 8]
 [1 9 2]]

Matriz de funciones
[2 1 3]

Print de Variables
[x y z]
Entonces las nuevas matrices U,G


In [69]:
gauss(A,F)

(array([[ 9,  0,  9],
        [ 0,  9,  6],
        [ 0,  0, -5]]),
 array([2, 0, 2]))

In [70]:
U1=gauss(A,F)[0]
G1=gauss(A,F)[1]
solucionatras(U1,G1)
XX=solucionatras(U1,G1)

In [71]:
A@XX-F
#ESTO DEBE DAR CERO XDXDXDXDXDDXDXDXD

array([28.8       , 25.04444444, 21.62222222])