In [7]:
#dolittle factorixation
import sympy as sy
import numpy as np
import matplotlib.pyplot as plt

def lu(A, n):
 #funcion para descomponer inferior
    inf = [[0 for x in range(n)]
             for y in range(n)]
    #para descomponer superior
    sup = [[0 for x in range(n)]
             for y in range(n)]
 
    # Descomposicion
    for i in range(n):
 
        #Triangular Superior
        for k in range(i, n):
 
            # Suma L(i, j) * U(j, k)
            sum = 0
            for j in range(i):
                sum += (inf[i][j] * sup[j][k])
 
            # Evaluacion U(i, k)
            sup[i][k] = A[i][k] - sum
 
        # Triangular inferior
        for k in range(i, n):
            if (i == k):
                inf[i][i] = 1  # Diagonal as 1
            else:
 
                # Suma L(k, j) * U(j, i)
                sum = 0
                for j in range(i):
                    sum += (inf[k][j] * sup[j][i])
 
                # Evaluacion L(k, i)
                inf[k][i] = int((A[k][i] - sum) /
                                  sup[i][i])
 
    #Print
    print("Triangular Inferior\t\tTriangular Superior")
 
    # Display :
    for i in range(n):
 
        # Inferior
        for j in range(n):
            print(inf[i][j], end="\t")
        print("", end="\t")
 
        # Superior
        for j in range(n):
            print(sup[i][j], end="\t")
        print("")

A=np.random.randint(20,size=(4,4))
print('\nMatriz A')
print(A)
 
lu(A, 4)


Matriz A
[[ 4 10 12 11]
 [10 14  3 16]
 [12  6  1  2]
 [ 5  4 18  7]]
Triangular Inferior		Triangular Superior
1	0	0	0		4	10	12	11	
2	1	0	0		0	-6	-21	-6	
3	4	1	0		0	0	49	-7	
1	1	0	1		0	0	0	2	
